services:
#  golang-scheduler-earthquake:
#    container_name: golang-scheduler-earthquake
#    environment:
#      - TARGET_URL=http://host.docker.internal:8080/api/v1/ndms/earthquakes
#      - INTERVAL=3
#      - BODY_FILE=earthquake.json
#    build:
#      context: .
#    ports:
#      - 3000:8080

#   golang-scheduler-fire:
#     container_name: golang-scheduler-fire
#     environment:
#       - TARGET_URL=http://host.docker.internal:8080/api/v1/ndms/firestorms
#       - INTERVAL=3
#       - BODY_FILE=firestorm.json
#     build:
#       context: .
#     ports:
#       - 3001:8080

   golang-scheduler-flood:
     container_name: golang-scheduler-flood
     environment:
       - TARGET_URL=http://host.docker.internal:8080/api/v1/ndms/floods
       - INTERVAL=3
       - BODY_FILE=flood.json
     build:
       context: .
     ports:
       - 3002:8080